spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true

  jpa:
    open-in-view: false
    generate-ddl: true

    hibernate:
      ddl-auto: create
      format_sql: true