spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/businessCard
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    open-in-view: false
    generate-ddl: true

    hibernate:
      ddl-auto: create-drop
      format_sql: true